### ISSUE TITLE
User-Defined Defaults

### ISSUE THREAD

**Issue by mtkp** [joelittlejohn/clj-http-hystrix#8]
Add support for user-defined defaults. This would let users, for example, set a default timeout that will be the fallback if the value is not supplied, making global configuration much easier.

The defaults could be an optional argument when adding the hook:

``` clj
;; specify different defaults for threads and timeout, via optional argument to add-hook
(clj-http-hystrix.core/add-hook {:hystrix/threads 8
                                 :hystrix/timeout-ms 2500})

(clj-http/get "example.com" {:hystrix/command-key "example"})
;;=> {:hystrix/command-key "example"
;;    :hystrix/threads 8
;;    :hystrix/timeout-ms 2500
;;    ... rest are clj-http-hystrix defaults... }

;; or instead, use clj-http-hytrix defaults (unchanged)
(clj-http-hystrix.core/add-hook)
```

@joelittlejohn I'm happy to tackle this if you think its a reasonable feature to add.

**Comment by joelittlejohn** [comment]
Sounds like a great idea, and setting these when adding the hook sounds
good to me.

**Comment by mtkp** [comment]
@joelittlejohn opened PR #9 for this issue. If you have a chance, would appreciate a review!

**Comment by mtkp** [comment]
thanks!
